-- ============================================================
-- 040_fix_clinic_users_user_id_fkey.sql
--
-- clinic_users.user_id referenciava uma tabela `public.users` órfã —
-- não é populada por handle_new_user() (o trigger real de signup, que
-- só grava em accounts e profiles) nem por nenhum outro código deste
-- projeto. Provavelmente sobrou de um sistema anterior ao Supabase
-- Auth.
--
-- Efeito colateral descoberto ao investigar: várias linhas reais e
-- ativas (owners de outras clínicas do sistema, não dado de teste)
-- têm user_id que também não bate com auth.users — ou seja, essa
-- coluna nunca teve uma referência consistente em todo o histórico da
-- tabela. Por isso NÃO recriamos como FK estrita para auth.users
-- (quebraria a migração de novo, e mexer nessas linhas é uma decisão
-- de dados que não é nossa pra tomar). Só removemos a constraint
-- quebrada, sem substituto — libera inserts com um user_id de login
-- real (o caso que importa: criar clínica nova, convite de equipe)
-- sem tocar em nenhuma linha existente.
--
-- Idempotente.
-- ============================================================

ALTER TABLE clinic_users DROP CONSTRAINT IF EXISTS clinic_users_user_id_fkey;
